# Generated by Django 2.2.2 on 2019-06-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(choices=[('Другое', 'Другое'), ('Аванс', 'Аванс'), ('Зарплата', 'Зарплата'), ('Социальные выплаты', 'Социальные выплаты')], default='Другое', max_length=25, verbose_name='Категория')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Комментарий')),
                ('price', models.FloatField(default=0, verbose_name='Сумма')),
                ('created_at', models.DateField(verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Записи о доходах',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(choices=[('Без категории', 'Без категории'), ('Комунальные услуги', 'Комунальные услуги'), ('Продуктовые покупки', 'Продуктовые покупки'), ('Товары для дома', 'Товары для дома'), ('Одежда, обувь, аксессуары', 'Одежда, обувь, аксессуары'), ('Образование', 'Образование'), ('Лекарства и медицина', 'Лекарства и медицина'), ('Автомобиль/транспорт', 'Автомобиль/транспорт'), ('Развлечения', 'Развлечения'), ('Хобби', 'Хобби'), ('Личные траты', 'Личные траты')], default='Без категории', max_length=25, verbose_name='Категория')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Комментарий')),
                ('price', models.FloatField(default=0, verbose_name='Сумма')),
                ('created_at', models.DateField(verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Записи о расходах',
                'ordering': ['-created_at'],
            },
        ),
    ]
